### ISSUE TITLE
When I run the command,I got the error!

### ISSUE THREAD

**Issue by zhushengwen** [pixelb/crudini#42]
Traceback (most recent call last):
  File "./crudini", line 916, in <module>
    sys.exit(main())
  File "./crudini", line 913, in main
    return crudini.run()
  File "./crudini", line 815, in run
    self.mconf = self.parse_file('-', preserve_case=True)
  File "./crudini", line 610, in parse_file
    conf = self._parse_file(filename, preserve_case=preserve_case)
  File "./crudini", line 594, in _parse_file
    conf = CrudiniConfigParser(preserve_case=preserve_case)
  File "./crudini", line 184, in __init__
    iniparse.change_comment_syntax('%;#', allow_rem=False)
AttributeError: 'module' object has no attribute 'change_comment_syntax'

**Comment by pixelb** [comment]
Wow you must have a very old version of iniparse. I think that option was added in version 3.2
What system are you using. If using pip then I can address this by specifying the version dependency on iniparse >= 3.2 in dependencies
